### ISSUE TITLE
Stata error -invalid syntax- when running 6. Logic checks

### ISSUE THREAD

**Issue by mayaian93** [PovertyAction/high-frequency-checks#158]
Hello, 

While running the hfc, all the checks run fine but the logic checks. Logic checks run ok only if I do not specify a condition in the if_condition column of the input sheet. As soon as I specify a simple condition, I get the stata error - invalid syntax -. I uploaded a picture that shows how I am specifying the condition. 

Can you please help to understand what's the issue here? 

Thanks,
Maya

![hfc logic checks](https://user-images.githubusercontent.com/62093248/79375782-d9bfc380-7f61-11ea-8ee9-34d03b20c865.JPG)

**Comment by luizaandrade** [comment]
Hi @rsandino and team,

I was helping Maya above debug this issue and we figured out that the problem was coming from the import of the excel sheet: the condition being tested uses the `assert` from one line and the `if_condition` from the following line.

so in the example above, it would run the following code:
`assert num_spouses <= 1
assert num_parents <=2 if primary_respondent_male == 9
assert male_summon == 0 if`

The last line is what causes the invalid syntax error.
Is this a problem that you have heard of in the past?

Cheers,

**Comment by iparesearch** [comment]
Hi @mayaian93 and @luizaandrade, apologies for the delay! I looks like this is a bug caused by the way the conditions are parsed, which has a problem if there are not an equal number of assertions and conditions. I have adjusted the code in a different branch so we can test it before merging to master. Can you use the code `ipacheck update hotfix` and try running again to see if it is resolved?

**Comment by luizaandrade** [comment]
wow, that was quick! thank you so much. I think it's a bit late on @mayaian93's time zone now, but we will let you know if it worked as soon as she runs it.

**Comment by Odoulami** [comment]
Hi @rsandino,
I'm part of the same team as @mayaian93 and @luizaandrade. I and another team member tried the solution you suggested. It runs fine and we expand it to another bunch of checks which are successful as well.

**Comment by rsandino** [comment]
Thanks for the update! I will merge this into the main branch so that
everyone can use it. New users will just need to use ipacheck update to
ensure they are up to date.

**Comment by mayaian93** [comment]
Hello @rsandino, 

Right now the HFC number 6 runs well and we manage to get the output file with the logic section. However, from the output file we can see that there is an issue with how the program is reading the if_condition column. Sometimes the if_condition is not read at all, sometimes it is read well and sometimes the if_condition belonging to another line it is applied. 

Is there way you can help us with this issue? 

Thanks a lo!
