### ISSUE TITLE
ipacheckcorrections | All corrections not applied

### ISSUE THREAD

**Issue by emawbgit** [PovertyAction/high-frequency-checks#177]
Hello, I have a file where I have written all the corrections (corrections_pp.xlsm; constraints_plotroster):
![image](https://github.com/PovertyAction/high-frequency-checks/assets/65594313/65eda30c-1506-4f40-8273-0ba4792f01e9).
 
When I try to run the command, all the corrections fail. Any hint on why that would be the case?
![image](https://github.com/PovertyAction/high-frequency-checks/assets/65594313/12e7779e-73f2-4106-bbaa-a4219e45bbc7)

Attached the log file
[ipacheckcorrections_error.log](https://github.com/PovertyAction/high-frequency-checks/files/12739635/ipacheckcorrections_error.log)

Thankful for any hint

**Comment by saxena-prakhar** [comment]
Hello, I am using ipachecks and have been facing an issue with the progreport command. Whenever I run the do file I get this _merge not found error. Could you please suggest what might be the issue here? I am using a Macbook.

<img width="1039" alt="Screenshot 2023-10-02 at 2 47 23 PM" src="https://github.com/PovertyAction/high-frequency-checks/assets/144927311/119dd8bd-5cec-40c7-8511-b713fafb73f8">

**Comment by iabaako** [comment]
Hi @saxena-prakhar, 

Thanks for reaching out. 

Unfortunately, we no longer maintain the `progreport` command because we have adopted its into a new command `ipactracksurvey`. `ipatracksurvey` is part of the new DMS 4 package and you can install it with the command `net install ipacheck, all replace from("https://raw.githubusercontent.com/PovertyAction/high-frequency-checks/master")`. **Please note:**  Running this command will replace your current version DMS 3 with DMS 4. If you only want to use the `ipactracksurvey` command without disrupting your workflow, then you should download and place the [source code](https://github.com/PovertyAction/high-frequency-checks/blob/master/ado/ipatracksurvey.ado) + [helpfile](https://github.com/PovertyAction/high-frequency-checks/blob/master/sthlp/ipatracksurvey.sthlp) for this command in your personal ado directory.  

You can get some information about the DMS 4 command on the [wiki page](https://github.com/PovertyAction/high-frequency-checks/wiki/Exercise).
