### ISSUE TITLE
Constantly get tempfile errors when running the template

### ISSUE THREAD

**Issue by catonbrewster** [PovertyAction/high-frequency-checks#38]
Constantly get this error: _file C:\Users\CBREWS~1.IPA\AppData\Local\Temp\ST_0d000005.tmp is read-only; cannot be modified  or erased_  

Often can work around it by just rerunning the do file a few times until it runs through but should figure out why this is happening. 

Need to start tracking for which checks this is happening.

**Comment by kelseylarson** [comment]
I think this problem might be caused by Box Sync problems: if Box tries to pull the changes you're making to upload to the server at the same time the HFC code is trying to make a new version of the file, you hit this error. Some people have gotten it to stop happening by telling Box not to sync while they're running the HFC code.
